### ISSUE TITLE
error fatal script de creación de bd

### ISSUE THREAD

**Issue by arodriguezsauces** [Rodrigerzur/203DWESProyectoTema5#1]
Es increíble!! **with grant option,** pero es un "**amancio**" 
y como es posible que no compruebes si la base de datos no existe antes de crearla

scriptDB/CreaDB203DWESProyectoTema4Desarrollo.sql

**Comment by Rodrigerzur** [comment]
Ya esta solucionado lo que pasa que hace mucho que no actualizaba.

En el momento que escribo las bases de datos deberían de funcionar en 1&1 y no en desarrollo

**Comment by arodriguezsauces** [comment]
Solucionado en la versión e6b6afcd7d720e0d209c2b4275d459f9cfd31606
